language: python
python:
  - "3.9"
# command to install dependencies
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - "pip install coverage"
  - "pip install coveralls"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  - "coverage run --source=. --omit=./test/* -m pytest"
after_success:
  coveralls
